services:
  mongodb_boilerplate:
    container_name: mongodb_boilerplate
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

    volumes:
      - ./mongodb_boilerplate:/data/db
volumes:
  mongodb_boilerplate:
